class HomePageLocators():
    button_menu_xpath = "//div[@class='bm-burger-button']"
    button_reset_id = "reset_sidebar_link"
    button_allitems_id = "inventory_sidebar_link"
    button_about_id = "about_sidebar_link"
    button_logout_id = "logout_sidebar_link"
    app_logo_css = ".app_logo"
    button_checkout_css = ".shopping_cart_link"
    button_sort_css = ".product_sort_container"
    button_addtocart_xpath = ".//button[@class='btn btn_primary btn_small btn_inventory ']"
    inventory_item_css = ".inventory_item_name"
    price_css = ".inventory_item_price"